# Generated by Django 4.2 on 2025-02-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_features", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="avg_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
